// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_thpylXAobvf9lYHLpBdy3svu6ouQMbA',
    appId: '1:434440546796:web:5dc5a14de4d0fdb90238c9',
    messagingSenderId: '434440546796',
    projectId: 'zamir-music-app',
    authDomain: 'zamir-music-app.firebaseapp.com',
    storageBucket: 'zamir-music-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEPfdRblPDcAJ3utElaQKDBFoLkgFsuo8',
    appId: '1:434440546796:android:017d1f69955029790238c9',
    messagingSenderId: '434440546796',
    projectId: 'zamir-music-app',
    storageBucket: 'zamir-music-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7oW-OH1AkJpeMVViwZTvKIzZMKFBNUx8',
    appId: '1:434440546796:ios:aeca4be0ba1d661a0238c9',
    messagingSenderId: '434440546796',
    projectId: 'zamir-music-app',
    storageBucket: 'zamir-music-app.firebasestorage.app',
    iosBundleId: 'com.example.zamir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7oW-OH1AkJpeMVViwZTvKIzZMKFBNUx8',
    appId: '1:434440546796:ios:aeca4be0ba1d661a0238c9',
    messagingSenderId: '434440546796',
    projectId: 'zamir-music-app',
    storageBucket: 'zamir-music-app.firebasestorage.app',
    iosBundleId: 'com.example.zamir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_thpylXAobvf9lYHLpBdy3svu6ouQMbA',
    appId: '1:434440546796:web:388219aa1f5fb2df0238c9',
    messagingSenderId: '434440546796',
    projectId: 'zamir-music-app',
    authDomain: 'zamir-music-app.firebaseapp.com',
    storageBucket: 'zamir-music-app.firebasestorage.app',
  );
}
