// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Add web config from zamir-cd6b1 Firebase console if needed
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHd_5ekqlZPQ29gaxjczoUXnnMN8ct6Xo',
    appId: '1:768926448470:web:placeholder',
    messagingSenderId: '768926448470',
    projectId: 'zamir-cd6b1',
    authDomain: 'zamir-cd6b1.firebaseapp.com',
    storageBucket: 'zamir-cd6b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHd_5ekqlZPQ29gaxjczoUXnnMN8ct6Xo',
    appId: '1:768926448470:android:90fac754986d03ac5f74f7',
    messagingSenderId: '768926448470',
    projectId: 'zamir-cd6b1',
    storageBucket: 'zamir-cd6b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVfAeDfg9ixNqYnQOg73WR2x6Ec02lbeg',
    appId: '1:768926448470:ios:36d2ba92be6b64355f74f7',
    messagingSenderId: '768926448470',
    projectId: 'zamir-cd6b1',
    storageBucket: 'zamir-cd6b1.firebasestorage.app',
    iosBundleId: 'com.devvmichael.zamir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVfAeDfg9ixNqYnQOg73WR2x6Ec02lbeg',
    appId: '1:768926448470:ios:36d2ba92be6b64355f74f7',
    messagingSenderId: '768926448470',
    projectId: 'zamir-cd6b1',
    storageBucket: 'zamir-cd6b1.firebasestorage.app',
    iosBundleId: 'com.devvmichael.zamir',
  );

  // TODO: Add windows config from zamir-cd6b1 Firebase console if needed
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHd_5ekqlZPQ29gaxjczoUXnnMN8ct6Xo',
    appId: '1:768926448470:web:placeholder',
    messagingSenderId: '768926448470',
    projectId: 'zamir-cd6b1',
    authDomain: 'zamir-cd6b1.firebaseapp.com',
    storageBucket: 'zamir-cd6b1.firebasestorage.app',
  );
}
